name: Deploy

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      app-version:
        required: true
        type: string
      distribution-channel:
        required: true
        type: string

permissions:
  contents: write

defaults:
  run:
    shell: 'bash'

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_audit: false
  npm_config_fund: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.distribution-channel}}
      url: https://github.com/${{github.repository}}/releases/tag/v${{inputs.app-version}}
    steps:
      - name: Download compiled app
        uses: actions/download-artifact@v8
        with:
          pattern: "${{inputs.project-name}}-*"
          path: dist
          merge-multiple: true
      
      - run: ls -la
        working-directory: ./
      - run: ls -la dist
        working-directory: ./
      
      - name: zip mac x86 without a docker container (the year is 20XX)
        run: zip -r ./unsigned/${{inputs.project-name}}-${{inputs.app-version}}-mac-x86 ./dist/mac

      - name: zip mac arm without a docker container (the year is 20XX)
        run: zip -r ./unsigned/${{inputs.project-name}}-${{inputs.app-version}}-mac-arm64 ./dist/mac-arm64
      
      - name: zip linux without a docker container (the year is 20XX)
        run: zip -r ./unsigned/${{inputs.project-name}}-${{inputs.app-version}}-ubuntu ./dist/linux-unpacked

      - name: zip windows without a docker container (the year is 20XX)
        run: zip -r ./unsigned/${{inputs.project-name}}-${{inputs.app-version}}-windows ./dist/win-unpacked

      # - name: zip mac x86 folder
      #   uses: somaz94/compress-decompress@v1
      #   with:
      #     command: compress
      #     source: ./dist/mac
      #     format: zip
      #     dest: ./unsigned
      #     destfilename: ${{inputs.project-name}}-${{inputs.app-version}}-mac-x86
      
      # - name: zip mac arm folder
      #   uses: somaz94/compress-decompress@v1
      #   with:
      #     command: compress
      #     source: ./dist/mac-arm64
      #     format: zip
      #     dest: ./unsigned
      #     destfilename: ${{inputs.project-name}}-${{inputs.app-version}}-mac-arm64
      
      # - name: zip linux folder
      #   uses: somaz94/compress-decompress@v1
      #   with:
      #     command: compress
      #     source: ./dist/linux-unpacked
      #     format: zip
      #     dest: ./unsigned
      #     destfilename: ${{inputs.project-name}}-${{inputs.app-version}}-ubuntu

      # - name: zip windows folder
      #   uses: somaz94/compress-decompress@v1
      #   with:
      #     command: compress
      #     source: ./dist/win-unpacked
      #     format: zip
      #     dest: ./unsigned
      #     destfilename: ${{inputs.project-name}}-${{inputs.app-version}}-windows
      
      - run: ls -la unsigned
        working-directory: ./

      # - run: gh release create v${{inputs.app-version}} unsigned/${{inputs.project-name}}* dist/latest*.yml --repo ${{github.repository}}
      #   env:
      #     GH_TOKEN: ${{ github.token }}
