name: Deploy

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      app-version:
        required: true
        type: string
      distribution-channel:
        required: true
        type: string

permissions:
  contents: write

defaults:
  run:
    shell: 'bash'

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_audit: false
  npm_config_fund: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.distribution-channel}}
      url: https://github.com/${{github.repository}}/releases/tag/v${{inputs.app-version}}
    steps:
      - name: Download compiled app
        uses: actions/download-artifact@v8
        with:
          pattern: "${{inputs.project-name}}-*"
          path: dist
          merge-multiple: true
      
      - run: ls -la
        working-directory: ./
      - run: ls -la dist
        working-directory: ./
      
      # - name: zip linux folder
      #   uses: somaz94/compress-decompress@v1
      #   with:
      #     command: compress
      #     source: 
      #   if 

      # - run: gh release create v${{inputs.app-version}} dist/${{inputs.project-name}}* dist/latest*.yml --repo ${{github.repository}}
      #   env:
      #     GH_TOKEN: ${{ github.token }}
